name: dskus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - arch-py
  - matplotlib
  - scikit-learn
  - altair
  - vega_datasets
  - pandas
  - seaborn
  - netcdf4 
  - h5netcdf
  - hdf5
  - dask
  - ipykernel
  - cartopy=0.19.0.post1
  - xarray
  - urllib2
  - chardet
  - requests
  - bokeh